global using CommonBasicLibraries.CollectionClasses;
global using jj1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.JsonSerializers.SystemTextJsonStrings;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using CommonBasicLibraries.DatabaseHelpers.ConditionClasses;
global using CommonBasicLibraries.DatabaseHelpers.Extensions;
global using CommonBasicLibraries.DatabaseHelpers.MiscClasses;
global using CommonBasicLibraries.DatabaseHelpers.MiscInterfaces;
global using ss1 = CommonBasicLibraries.DatabaseHelpers.MiscClasses.StaticHelpers;
global using CommonBasicLibraries.DatabaseHelpers.EntityInterfaces;
global using AdoNetHelpersLibrary.ConnectionHelpers;
global using System.Data.Common;
global using System.Data;
